# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-11 19:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusDropArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'busrv_busDropArea',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_name', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('bus_description', models.TextField()),
                ('type', models.CharField(choices=[('AC', 'AC Bus'), ('NAC', 'Non AC bus')], default='AC', max_length=10)),
                ('arriving_time', models.TimeField()),
                ('depature_time', models.TimeField()),
                ('fare', models.DecimalField(decimal_places=2, max_digits=9)),
                ('no_of_seats', models.IntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='images/bus/main/')),
            ],
            options={
                'db_table': 'busrv_busInfo',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusPickArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'busrv_busPickArea',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='businfo',
            name='arriving_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.BusPickArea'),
        ),
        migrations.AddField(
            model_name='businfo',
            name='depature_at',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.BusDropArea'),
        ),
    ]
