# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-15 18:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookAticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('P', 'Pending'), ('C', 'Confrimed')], default='P', max_length=2)),
                ('ip_address', models.GenericIPAddressField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('booking_seats_num', models.IntegerField(default=1)),
                ('fare', models.DecimalField(decimal_places=2, max_digits=9)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.BusInfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
